Spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/overwatch
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql

  mail:
    host: smtp.gmail.com
    port: 587
    username: playzoneguichet@gmail.com
    password: yywbrfhwfrwfhaix
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8081
